// Package proxy generates a Caddyfile from the live state and reloads Caddy so
// that <name>.localhost routes to wherever the project is actually running.
package proxy

import (
	"fmt"
	"os"
	"os/exec"
	"sort"
	"strings"

	"github.com/antoniojosev/pm/internal/config"
)

// Route maps a hostname to the live upstream port.
type Route struct {
	Host string // e.g. myapp.localhost
	Port int
}

// Generate renders a Caddyfile. The daemon itself is always routed at
// pm.localhost -> daemonPort so the dashboard has a stable name. Each site is
// served under both <label>.localhost (local) and <label><RemoteSuffix>
// (remote, e.g. .pm over Tailscale) when a remote suffix is configured.
func Generate(routes []Route, daemonPort int) string {
	var b strings.Builder
	b.WriteString("# Generated by pm — do not edit by hand.\n")
	b.WriteString("{\n\tauto_https off\n}\n\n")

	// stable dashboard route
	fmt.Fprintf(&b, "%s {\n%s}\n\n", siteAddrs("pm"), proxyBlock(daemonPort))

	sort.Slice(routes, func(i, j int) bool { return routes[i].Host < routes[j].Host })
	for _, r := range routes {
		if r.Port == 0 || r.Host == "" || r.Host == "pm"+config.DNSSuffix {
			continue
		}
		label := strings.TrimSuffix(r.Host, config.DNSSuffix)
		fmt.Fprintf(&b, "%s {\n%s}\n\n", siteAddrs(label), proxyBlock(r.Port))
	}
	return b.String()
}

// proxyBlock renders the reverse_proxy directive for an upstream port. The
// Host header is rewritten to localhost so dev servers with host allowlists
// (Vite server.allowedHosts, Next.js, etc.) accept proxied requests without
// per-project config; the original host still reaches the app via the
// X-Forwarded-Host header that Caddy sets by default.
func proxyBlock(port int) string {
	return fmt.Sprintf("\treverse_proxy 127.0.0.1:%d {\n\t\theader_up Host localhost:%d\n\t}\n", port, port)
}

// siteAddrs builds the comma-separated Caddy site addresses for a label:
// always http://<label>.localhost and, when configured, http://<label><RemoteSuffix>.
func siteAddrs(label string) string {
	addrs := []string{fmt.Sprintf("http://%s%s:%d", label, config.DNSSuffix, config.ProxyPort)}
	if config.RemoteSuffix != "" {
		addrs = append(addrs, fmt.Sprintf("http://%s%s:%d", label, config.RemoteSuffix, config.ProxyPort))
	}
	return strings.Join(addrs, ", ")
}

// Write renders and writes the Caddyfile to disk.
func Write(path string, routes []Route, daemonPort int) error {
	return os.WriteFile(path, []byte(Generate(routes, daemonPort)), 0o644)
}

// Reload asks a running Caddy (started as a user service) to pick up the new
// Caddyfile without dropping connections. Silent no-op if caddy is absent.
func Reload(caddyfile string) error {
	if _, err := exec.LookPath("caddy"); err != nil {
		return nil
	}
	out, err := exec.Command("caddy", "reload", "--config", caddyfile, "--adapter", "caddyfile").CombinedOutput()
	if err != nil {
		return fmt.Errorf("caddy reload: %v: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

// Available reports whether the caddy binary is installed.
func Available() bool {
	_, err := exec.LookPath("caddy")
	return err == nil
}
