package proxy

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/antoniojosev/pm/internal/config"
)

func withRemoteSuffix(t *testing.T, s string) {
	t.Helper()
	prev := config.RemoteSuffix
	config.RemoteSuffix = s
	t.Cleanup(func() { config.RemoteSuffix = prev })
}

func TestGenerateDashboardRouteAlwaysPresent(t *testing.T) {
	withRemoteSuffix(t, "")
	out := Generate(nil, 9797)

	for _, want := range []string{
		"# Generated by pm",
		"auto_https off",
		"http://pm.localhost:80 {",
		"reverse_proxy 127.0.0.1:9797",
		"header_up Host localhost:9797",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("missing %q in:\n%s", want, out)
		}
	}
	if strings.Count(out, "reverse_proxy") != 1 {
		t.Fatalf("expected only the dashboard route:\n%s", out)
	}
}

func TestGenerateRoutes(t *testing.T) {
	withRemoteSuffix(t, "")
	routes := []Route{
		{Host: "web.localhost", Port: 5173},
		{Host: "api.localhost", Port: 8000},
		{Host: "pm.localhost", Port: 1234}, // reserved for the dashboard → skipped
		{Host: "dead.localhost", Port: 0},  // not running → skipped
		{Host: "", Port: 3000},             // nameless → skipped
	}
	out := Generate(routes, 9797)

	api := strings.Index(out, "http://api.localhost:80 {")
	web := strings.Index(out, "http://web.localhost:80 {")
	if api < 0 || web < 0 {
		t.Fatalf("routes missing:\n%s", out)
	}
	if api > web {
		t.Fatal("routes must be sorted by host for a stable Caddyfile")
	}
	if !strings.Contains(out, "reverse_proxy 127.0.0.1:5173 {\n\t\theader_up Host localhost:5173") {
		t.Fatalf("web upstream not rendered:\n%s", out)
	}
	if strings.Contains(out, "dead.localhost") || strings.Contains(out, ":1234") || strings.Contains(out, ":3000") {
		t.Fatalf("skipped routes leaked into the Caddyfile:\n%s", out)
	}
	if strings.Count(out, "reverse_proxy") != 3 {
		t.Fatalf("expected dashboard + 2 routes:\n%s", out)
	}
}

func TestGenerateIsDeterministic(t *testing.T) {
	withRemoteSuffix(t, "")
	a := Generate([]Route{{Host: "b.localhost", Port: 2}, {Host: "a.localhost", Port: 1}}, 9797)
	b := Generate([]Route{{Host: "a.localhost", Port: 1}, {Host: "b.localhost", Port: 2}}, 9797)
	if a != b {
		t.Fatal("same routes in different order produced different output")
	}
}

func TestGenerateWithRemoteSuffix(t *testing.T) {
	withRemoteSuffix(t, ".pm")
	out := Generate([]Route{{Host: "web.localhost", Port: 5173}}, 9797)

	if !strings.Contains(out, "http://pm.localhost:80, http://pm.pm:80 {") {
		t.Fatalf("dashboard should answer on both suffixes:\n%s", out)
	}
	if !strings.Contains(out, "http://web.localhost:80, http://web.pm:80 {") {
		t.Fatalf("route should answer on both suffixes:\n%s", out)
	}
}

func TestSiteAddrs(t *testing.T) {
	withRemoteSuffix(t, "")
	if got := siteAddrs("x"); got != "http://x.localhost:80" {
		t.Fatalf("siteAddrs = %q", got)
	}
	withRemoteSuffix(t, ".tail")
	if got := siteAddrs("x"); got != "http://x.localhost:80, http://x.tail:80" {
		t.Fatalf("siteAddrs = %q", got)
	}
}

func TestWrite(t *testing.T) {
	withRemoteSuffix(t, "")
	path := filepath.Join(t.TempDir(), "Caddyfile")
	if err := Write(path, []Route{{Host: "web.localhost", Port: 5173}}, 9797); err != nil {
		t.Fatalf("Write: %v", err)
	}
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(b) != Generate([]Route{{Host: "web.localhost", Port: 5173}}, 9797) {
		t.Fatal("file content differs from Generate output")
	}
}

func TestReloadWithoutCaddyIsNoop(t *testing.T) {
	t.Setenv("PATH", t.TempDir()) // no caddy binary reachable
	if Available() {
		t.Fatal("caddy should not be available with an empty PATH")
	}
	if err := Reload(filepath.Join(t.TempDir(), "Caddyfile")); err != nil {
		t.Fatalf("Reload without caddy should be a no-op, got %v", err)
	}
}
